d /var/lib/quickprice 0700 quickprice quickprice -
d /var/lib/quickprice/config 0700 quickprice quickprice -
z /var/lib/quickprice/config/admin-account.json 0600 quickprice quickprice -
d /etc/quickprice 0750 root quickprice -
