// QuickPrice Power Query for Microsoft 365 Excel on Windows and macOS.
//
// Create three required Text parameters before pasting this query:
//   QuickPriceBaseUrl = https://price.example.com
//   QuickPriceApiKey  = the raw key generated by `quickprice hash-key --generate`
//   QuickPriceSymbols = BTC:USDC,WBETH:USDC,STETH:USDC,WSTETH:USDC,QQQM:USD,EUR:GBP,CNH:HKD
//
// Configure the origin as Anonymous. Authentication is carried only by the
// X-API-Key header. Never append a key to a URL.

let
    BaseUrl = Text.TrimEnd(Text.Trim(QuickPriceBaseUrl), "/"),
    CheckedBaseUrl =
        if BaseUrl = "" then
            error Error.Record("QuickPrice configuration", "QuickPriceBaseUrl must not be empty", null)
        else if not Text.StartsWith(Text.Lower(BaseUrl), "https://") then
            error Error.Record("QuickPrice configuration", "QuickPriceBaseUrl must use HTTPS", null)
        else
            BaseUrl,
    CheckedApiKey =
        if Text.Trim(QuickPriceApiKey) = "" then
            error Error.Record("QuickPrice configuration", "QuickPriceApiKey must not be empty", null)
        else
            QuickPriceApiKey,
    Symbols = List.Distinct(
        List.Select(
            List.Transform(Text.Split(QuickPriceSymbols, ","), each Text.Upper(Text.Trim(_))),
            each _ <> ""
        )
    ),
    CheckedSymbols =
        if List.Count(Symbols) = 0 then
            error Error.Record("QuickPrice configuration", "QuickPriceSymbols must not be empty", null)
        else
            Symbols,
    Batches = List.Split(CheckedSymbols, 100),

    NestedField = (value as any, field as text) as any =>
        if value is record then Record.FieldOrDefault(value, field, null) else null,
    ChangeValue = (changes as any, window as text, field as text) as any =>
        let WindowValue = NestedField(changes, window)
        in
            if WindowValue is record then
                Record.FieldOrDefault(WindowValue, field, null)
            else if field = "percent" then
                WindowValue
            else
                null,

    RequestBatch = (batch as list) as record =>
        let
            RawResponse = Web.Contents(
                CheckedBaseUrl,
                [
                    RelativePath = "v1/quotes",
                    Query = [symbols = Text.Combine(batch, ",")],
                    Headers = [
                        #"X-API-Key" = CheckedApiKey,
                        Accept = "application/json"
                    ],
                    Timeout = #duration(0, 0, 0, 30),
                    ManualStatusHandling = {400, 401, 404, 422, 429, 503}
                ]
            ),
            HttpStatus = try Value.Metadata(RawResponse)[Response.Status] otherwise 200,
            Payload = Json.Document(RawResponse),
            ResponseErrors = Record.FieldOrDefault(Payload, "errors", {}),
            FirstErrorMessage =
                if ResponseErrors is list and List.Count(ResponseErrors) > 0 and ResponseErrors{0} is record then
                    Text.From(Record.FieldOrDefault(ResponseErrors{0}, "message", "Request failed"))
                else
                    "Request failed"
        in
            if HttpStatus <> 200 then
                error Error.Record(
                    "QuickPrice HTTP " & Number.ToText(HttpStatus),
                    FirstErrorMessage,
                    Payload
                )
            else
                Payload,

    Payloads = List.Transform(Batches, each RequestBatch(_)),
    Data = List.Combine(List.Transform(Payloads, each Record.FieldOrDefault(_, "data", {}))),
    ResponseErrors = List.Combine(List.Transform(Payloads, each Record.FieldOrDefault(_, "errors", {}))),
    ApiPartial = List.AnyTrue(List.Transform(Payloads, each Record.FieldOrDefault(_, "partial", false))),
    QuoteRows = Table.FromRecords(
        Data,
        {
            "symbol", "base", "quote", "name", "description", "asset_class", "asset_type",
            "reward_accrual_mode", "underlying_asset", "price", "price_basis", "as_of", "market_status",
            "changes", "dividend", "estimated_annual_yield", "source", "quality"
        },
        MissingField.UseNull
    ),

    With1h = Table.AddColumn(QuoteRows, "change_1h_percent", each ChangeValue([changes], "1h", "percent"), type nullable number),
    With4h = Table.AddColumn(With1h, "change_4h_percent", each ChangeValue([changes], "4h", "percent"), type nullable number),
    With1d = Table.AddColumn(With4h, "change_1d_percent", each ChangeValue([changes], "1d", "percent"), type nullable number),
    With1w = Table.AddColumn(With1d, "change_1w_percent", each ChangeValue([changes], "1w", "percent"), type nullable number),
    With1mo = Table.AddColumn(With1w, "change_1mo_percent", each ChangeValue([changes], "1mo", "percent"), type nullable number),
    With1y = Table.AddColumn(With1mo, "change_1y_percent", each ChangeValue([changes], "1y", "percent"), type nullable number),
    WithProvider = Table.AddColumn(With1y, "source_provider", each NestedField([source], "provider"), type nullable text),
    WithFeed = Table.AddColumn(WithProvider, "source_feed", each NestedField([source], "feed"), type nullable text),
    WithStale = Table.AddColumn(WithFeed, "is_stale", each NestedField([quality], "stale"), type nullable logical),
    WithStaleness = Table.AddColumn(WithStale, "staleness_ms", each NestedField([quality], "staleness_ms"), Int64.Type),
    WithYield = Table.AddColumn(WithStaleness, "estimated_annual_yield_percent", each NestedField([estimated_annual_yield], "percent"), type nullable number),
    WithYieldType = Table.AddColumn(WithYield, "yield_rate_type", each NestedField([estimated_annual_yield], "rate_type"), type nullable text),
    WithYieldMode = Table.AddColumn(WithYieldType, "yield_accrual_mode", each NestedField([estimated_annual_yield], "accrual_mode"), type nullable text),
    WithYieldEstimate = Table.AddColumn(WithYieldMode, "yield_is_estimate", each NestedField([estimated_annual_yield], "is_estimate"), type nullable logical),
    WithYieldFallback = Table.AddColumn(WithYieldEstimate, "yield_fallback_level", each NestedField([estimated_annual_yield], "fallback_level"), Int64.Type),
    WithYieldWindow = Table.AddColumn(WithYieldFallback, "yield_observation_window_days", each NestedField([estimated_annual_yield], "observation_window_days"), type nullable number),
    WithYieldQuality = Table.AddColumn(WithYieldWindow, "yield_quality", each NestedField(NestedField([estimated_annual_yield], "quality"), "confidence"), type nullable text),
    WithDividendYield = Table.AddColumn(WithYieldQuality, "dividend_yield_percent", each NestedField([dividend], "yield_percent"), type nullable number),
    ErrorSummary = Text.Combine(
        List.Transform(
            ResponseErrors,
            each
                if _ is record then
                    Text.Combine(
                        List.RemoveNulls({
                            try Text.From(Record.FieldOrDefault(_, "symbol", null)) otherwise null,
                            try Text.From(Record.FieldOrDefault(_, "code", null)) otherwise null,
                            try Text.From(Record.FieldOrDefault(_, "message", null)) otherwise null
                        }),
                        ": "
                    )
                else
                    Text.From(_)
        ),
        " | "
    ),
    WithApiPartial = Table.AddColumn(WithDividendYield, "api_partial", each ApiPartial, type logical),
    WithApiErrors = Table.AddColumn(WithApiPartial, "api_errors", each if ErrorSummary = "" then null else ErrorSummary, type nullable text)
in
    WithApiErrors
