"""The instruments shipped with QuickPrice itself."""

from __future__ import annotations

from .plugin_api import (
    AssetClass,
    InstrumentPlugin,
    InstrumentSpec,
    MarketCalendar,
    RewardAccrualMode,
    YieldStrategy,
)

BUILTIN_PLUGIN = InstrumentPlugin(
    plugin_id="builtin",
    version="1.1.0",
    provider_installer="quickprice.providers.wiring:install_builtin_provider_routes",
    instruments=(
        InstrumentSpec(
            symbol="BTC:USDC",
            base="BTC",
            quote="USDC",
            name="Bitcoin",
            description="Bitcoin spot price quoted in USD Coin.",
            asset_class=AssetClass.CRYPTO,
            asset_type="spot_crypto",
            price_basis="last_trade",
            quote_poll_seconds=1.0,
        ),
        InstrumentSpec(
            symbol="ETH:USDC",
            base="ETH",
            quote="USDC",
            name="Ethereum",
            description="Ether spot price quoted in USD Coin.",
            asset_class=AssetClass.CRYPTO,
            asset_type="spot_crypto",
            price_basis="last_trade",
            quote_poll_seconds=1.0,
        ),
        InstrumentSpec(
            symbol="WBETH:USDC",
            base="WBETH",
            quote="USDC",
            name="Wrapped Binance Beacon ETH",
            description=(
                "A value-accruing liquid-staking token whose market price is derived "
                "from synchronized component markets."
            ),
            asset_class=AssetClass.CRYPTO,
            asset_type="liquid_staking_token",
            price_basis="synthetic_cross",
            yield_strategy=YieldStrategy.STAKING_PROVIDER_METRIC,
            reward_accrual_mode=RewardAccrualMode.VALUE_ACCRUING,
            underlying_asset="ETH",
            quote_poll_seconds=1.0,
        ),
        InstrumentSpec(
            symbol="QQQM:USD",
            base="QQQM",
            quote="USD",
            name="Invesco NASDAQ 100 ETF",
            description="An exchange-traded fund tracking the NASDAQ-100 Index.",
            asset_class=AssetClass.EQUITY,
            asset_type="equity_etf",
            price_basis="last_trade",
            dividend_strategy="latest_regular_cash_annualized_x4",
            market_calendar=MarketCalendar.US_EQUITY,
            stale_after_seconds=120.0,
            quote_poll_seconds=5.0,
        ),
        InstrumentSpec(
            symbol="BOXX:USD",
            base="BOXX",
            quote="USD",
            name="Alpha Architect 1-3 Month Box ETF",
            description="An ETF seeking a Treasury-bill-like return through box spreads.",
            asset_class=AssetClass.BOND,
            asset_type="growth_bond_etf",
            price_basis="last_trade",
            yield_strategy=YieldStrategy.TREASURY_3M_PROXY_MINUS_EXPENSE,
            market_calendar=MarketCalendar.US_EQUITY,
            stale_after_seconds=120.0,
            quote_poll_seconds=5.0,
        ),
        InstrumentSpec(
            symbol="SGOV:USD",
            base="SGOV",
            quote="USD",
            name="iShares 0-3 Month Treasury Bond ETF",
            description="An ETF investing in United States Treasury bonds maturing within three months.",
            asset_class=AssetClass.BOND,
            asset_type="income_bond_etf",
            price_basis="last_trade",
            yield_strategy=YieldStrategy.LATEST_DISTRIBUTION_ANNUALIZED,
            market_calendar=MarketCalendar.US_EQUITY,
            stale_after_seconds=120.0,
            quote_poll_seconds=5.0,
        ),
        InstrumentSpec(
            symbol="USD:CNH",
            base="USD",
            quote="CNH",
            name="United States Dollar / Offshore Chinese Yuan",
            description="The offshore Chinese yuan value of one United States dollar.",
            asset_class=AssetClass.FX,
            asset_type="forex_pair",
            price_basis="mid",
            market_calendar=MarketCalendar.FX_24X5,
            stale_after_seconds=300.0,
            quote_poll_seconds=130.0,
        ),
        InstrumentSpec(
            symbol="HKD:CNH",
            base="HKD",
            quote="CNH",
            name="Hong Kong Dollar / Offshore Chinese Yuan",
            description="A synthetic offshore Chinese yuan price for one Hong Kong dollar.",
            asset_class=AssetClass.FX,
            asset_type="forex_pair",
            price_basis="synthetic_cross",
            market_calendar=MarketCalendar.FX_24X5,
            stale_after_seconds=1200.0,
            quote_poll_seconds=130.0,
        ),
    ),
)


def get_plugin() -> InstrumentPlugin:
    return BUILTIN_PLUGIN
